apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sim
    component: kubesim
  name: kubesim
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sim
      component: kubesim
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        app: sim
        component: kubesim
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: sim
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /bin/sh
        - -c
        - exec /bin/kubesim  --kubeconfig /root/.kube/config
          --port 9090  --config /etc/kubesim/scheduler-config-kubesim.yaml --skipinclusterlookup
          false --clientcertclientCA /etc/kubernetes/ssl/ca.pem --requestclientCAfile
          /etc/kubernetes/ssl/ca.pem --log-dir="/opt/kubesim" --log-file-max-size=180 --log-file="/opt/kubesim/kubesim.log"
          --logtostderr=false --stderrthreshold=1 --v=2
        env:
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: kubesim:0.0.1
        imagePullPolicy: IfNotPresent
        name: kubesim
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: k8s-config
        - mountPath: /root/.kube
          name: kube-config
        - mountPath: /opt/kubesim
          name: kube-sim-log
        - mountPath: /etc/kubesim/
          name: scheduler-kubesim-config
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/kubernetes
          type: Directory
        name: k8s-config
      - hostPath:
          path: /root/.kube
          type: Directory
        name: kube-config
      - hostPath:
          path: /k8s_log/kubesim
          type: ""
        name: kube-sim-log
      - configMap:
          name: scheduler-kubesim-config
        name: scheduler-kubesim-config
