apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
healthzBindAddress: "0.0.0.0:10261"
metricsBindAddress: "0.0.0.0:10261"
profiles:
- schedulerName: default-scheduler
  plugins:
    bind:
      enabled:
        - name: "KubesimBinder"
      disabled:
        - name: "DefaultBinder"
